# Generated by Django 5.0.1 on 2024-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True, verbose_name='URL-ссылка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='R20245123128648', max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
    ]
