# Generated by Django 5.0.1 on 2024-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_slug_alter_order_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='R20245123162031', max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
    ]
