# Generated by Django 4.2.7 on 2024-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Содержиние')),
                ('image', models.ImageField(upload_to='OurBenefits/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наше преимущество',
                'verbose_name_plural': ' Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.URLField(unique=True)),
                ('image', models.ImageField(upload_to='SocialMedia/', verbose_name='Изображение ссылки')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
