# Generated by Django 5.0.1 on 2024-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orangeMainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSectionBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='PromoSectionBG/', verbose_name='Изображение ссылки')),
            ],
            options={
                'verbose_name': 'Фон для promo_section',
                'verbose_name_plural': 'Фон для promo_section',
            },
        ),
    ]
