# Generated by Django 5.0.1 on 2024-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Categoty_2/', verbose_name='Фото 2 категории'),
        ),
    ]
