# Generated by Django 5.0.1 on 2024-01-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
        migrations.CreateModel(
            name='AdvantagesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, unique=True, verbose_name='Преимущество')),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Преимущество категории',
                'verbose_name_plural': 'Преимущества категорий',
            },
        ),
    ]
