# Generated by Django 5.0.1 on 2024-03-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_category_unique_together_advantagescategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ключ сессии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=13, unique=True, verbose_name='Промо-код')),
                ('value_discont', models.SmallIntegerField(verbose_name='% скидки по промо-коду')),
                ('create_code', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания промокода')),
                ('activate_code', models.DateTimeField(auto_now=True, verbose_name='Дата активации промокода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус действия промокода')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.usercart', verbose_name='Корзина покупок')),
            ],
            options={
                'verbose_name': 'Промо-код на скидку',
                'verbose_name_plural': 'Промо-коды на скидку',
            },
        ),
    ]
