# Generated by Django 5.0.1 on 2024-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_promocode_user_cart_id_alter_promocode_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='activate_code',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации промокода'),
        ),
    ]
