# Generated by Django 5.0.1 on 2024-04-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_promocode_activate_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'verbose_name': 'Корзина пользователя', 'verbose_name_plural': 'Корзина пользователя'},
        ),
        migrations.AddField(
            model_name='usercart',
            name='promo_code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.promocode', verbose_name='Промо-код'),
        ),
    ]
